<?php

namespace CrudBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * DataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataRepository extends \Doctrine\ORM\EntityRepository
{

}
